# Generated by Django 4.2.16 on 2024-12-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('realtor', 'Realtor'), ('user', 'User ')], default='user', max_length=10),
        ),
    ]
