# Generated by Django 5.1.3 on 2024-12-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='amenities',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='num_bathrooms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='num_bedrooms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='property_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='square_footage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='status',
            field=models.CharField(default='Available', max_length=50),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='property_videos/'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='virtual_tour_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
