# Generated by Django 5.1.3 on 2024-12-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_propertylisting_amenities_propertylisting_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='num_bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='num_bedrooms',
            field=models.IntegerField(default=1),
        ),
    ]
