# Generated by Django 4.2.16 on 2024-12-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_propertylisting_custom_property_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='sale_status',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], default='sale', max_length=10),
        ),
    ]
